# Generated by Django 5.0 on 2024-01-08 16:11

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_post_view"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="pictures",
            field=models.ImageField(
                blank=True, null=True, upload_to=blog.models.Post.user_directory_path
            ),
        ),
    ]
